# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ReactNativeStoreViewExample' do
	pod 'React', :subspecs => [
	    'Core',
	    'BatchedBridge',
	    'RCTImage',
	    'RCTText'
	    ], :path => '../node_modules/react-native'
	pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'ReactNativeStoreView', :path => '../node_modules/react-native-store-view'
end

target 'ReactNativeStoreViewExampleTests' do

end

