source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ReactNativeStoreView_Example', :exclusive => true do
  pod 'ReactNativeStoreView', :path => '../'
end

target 'ReactNativeStoreView_Tests', :exclusive => true do
  pod 'ReactNativeStoreView', :path => '../'

  
end
